# Generated by Django 4.2 on 2023-05-13 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ege_Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название варианта')),
                ('kim', models.CharField(db_index=True, max_length=8, verbose_name='КИМ')),
                ('description', models.CharField(max_length=250, null=True, verbose_name='Описание варианта')),
                ('level', models.CharField(max_length=50, null=True, verbose_name='Сложность')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата составления')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Открытый доступ')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
            },
        ),
        migrations.CreateModel(
            name='Ege_Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Название задания')),
                ('type', models.CharField(max_length=100, null=True, verbose_name='Тип задания (1-27)')),
                ('answer_1', models.CharField(max_length=120, null=True, verbose_name='Ответ на задание (основной)')),
                ('additional_1', models.CharField(max_length=120, null=True, verbose_name='Ответ на задание (основной_доп)')),
                ('answer_2', models.CharField(max_length=120, null=True, verbose_name='Ответ на задание (2)')),
                ('additional_2', models.CharField(max_length=120, null=True, verbose_name='Ответ на задание (доп_2)')),
                ('answer_3', models.CharField(max_length=120, null=True, verbose_name='Ответ на задание (3)')),
                ('additional_3', models.CharField(max_length=120, null=True, verbose_name='Ответ на задание (доп_3)')),
                ('answer_4', models.CharField(max_length=120, null=True, verbose_name='Ответ на задание (4)')),
                ('additional_4', models.CharField(max_length=120, null=True, verbose_name='Ответ на задание (доп_4)')),
                ('answer_5', models.CharField(max_length=120, null=True, verbose_name='Ответ на задание (5)')),
                ('additional_5', models.CharField(max_length=120, null=True, verbose_name='Ответ на задание (доп_5)')),
                ('answer_6', models.CharField(max_length=120, null=True, verbose_name='Ответ на задание (6)')),
                ('additional_6', models.CharField(max_length=120, null=True, verbose_name='Ответ на задание (доп_6)')),
                ('answer_7', models.CharField(max_length=120, null=True, verbose_name='Ответ на задание (7)')),
                ('additional_7', models.CharField(max_length=120, null=True, verbose_name='Ответ на задание (доп_7)')),
                ('answer_8', models.CharField(max_length=120, null=True, verbose_name='Ответ на задание (8)')),
                ('additional_8', models.CharField(max_length=120, null=True, verbose_name='Ответ на задание (доп_8)')),
                ('answer_9', models.CharField(max_length=120, null=True, verbose_name='Ответ на задание (9)')),
                ('additional_9', models.CharField(max_length=120, null=True, verbose_name='Ответ на задание (доп_9)')),
                ('answer_10', models.CharField(max_length=120, null=True, verbose_name='Ответ на задание (10)')),
                ('additional_10', models.CharField(max_length=120, null=True, verbose_name='Ответ на задание (доп_10)')),
                ('files_1', models.FileField(null=True, upload_to='', verbose_name='Файл_1')),
                ('files_2', models.FileField(null=True, upload_to='', verbose_name='Файл_2')),
                ('files_3', models.FileField(null=True, upload_to='', verbose_name='Файл_3')),
                ('files_4', models.FileField(null=True, upload_to='', verbose_name='Файл_4')),
                ('files_5', models.FileField(null=True, upload_to='', verbose_name='Файл_5')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('level', models.CharField(max_length=50, null=True, verbose_name='Уровень сложности')),
                ('kim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ege.ege_variants')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
