# Generated by Django 4.2 on 2023-05-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ege_exercise',
            name='content',
            field=models.TextField(null=True, verbose_name='Задание'),
        ),
    ]
