# Generated by Django 4.2 on 2023-05-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0002_ege_exercise_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ege_variants',
            name='description',
            field=models.TextField(max_length=250, null=True, verbose_name='Описание варианта'),
        ),
    ]
