# Generated by Django 4.2 on 2023-05-17 21:07

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0003_alter_ege_variants_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ege_exercise',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Задание'),
        ),
    ]
