# Generated by Django 4.2 on 2023-05-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0004_alter_ege_exercise_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ege_exercise',
            name='additional_1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ответ на задание (основной_доп)'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='additional_10',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ответ на задание (доп_10)'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='additional_2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ответ на задание (доп_2)'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='additional_3',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ответ на задание (доп_3)'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='additional_4',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ответ на задание (доп_4)'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='additional_5',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ответ на задание (доп_5)'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='additional_6',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ответ на задание (доп_6)'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='additional_7',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ответ на задание (доп_7)'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='additional_8',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ответ на задание (доп_8)'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='additional_9',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ответ на задание (доп_9)'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='answer_10',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ответ на задание (10)'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='answer_2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ответ на задание (2)'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='answer_3',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ответ на задание (3)'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='answer_4',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ответ на задание (4)'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='answer_5',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ответ на задание (5)'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='answer_6',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ответ на задание (6)'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='answer_7',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ответ на задание (7)'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='answer_8',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ответ на задание (8)'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='answer_9',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ответ на задание (9)'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='content',
            field=models.CharField(max_length=100, null=True, verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='files_1',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл_1'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='files_2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл_2'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='files_3',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл_3'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='files_4',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл_4'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='files_5',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл_5'),
        ),
    ]
