# Generated by Django 4.2 on 2023-06-02 16:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0006_alter_ege_exercise_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ege_exercise',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='kim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ege.ege_variants'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='level',
            field=models.CharField(choices=[('H', 'Сложный'), ('M', 'Средний'), ('L', 'Базовый')], max_length=50, verbose_name='Уровень сложности'),
        ),
        migrations.AlterField(
            model_name='ege_exercise',
            name='type',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27')], max_length=100, null=True, verbose_name='Тип задания (1-27)'),
        ),
        migrations.AlterField(
            model_name='ege_variants',
            name='level',
            field=models.CharField(choices=[('H', 'Сложный'), ('M', 'Средний'), ('L', 'Базовый')], max_length=50, null=True, verbose_name='Уровень'),
        ),
    ]
