# Generated by Django 4.2 on 2023-06-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('questions', models.TextField()),
                ('answers', models.TextField()),
                ('task_type', models.CharField(choices=[('math', 'Mathematics'), ('history', 'History'), ('science', 'Science')], max_length=20)),
                ('kim', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kim', models.CharField(max_length=8, unique=True)),
                ('tasks', models.ManyToManyField(to='informatica.task')),
            ],
        ),
    ]
