# Generated by Django 4.2 on 2023-06-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='kim',
        ),
    ]
