# Generated by Django 4.2 on 2023-06-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0002_remove_task_kim'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='number',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
