# Generated by Django 4.2 on 2023-06-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0003_task_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='number',
        ),
    ]
