# Generated by Django 4.2 on 2023-06-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0006_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedtask',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Открытый доступ'),
        ),
    ]
