# Generated by Django 4.2 on 2023-06-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0009_generatedtask_time_create_generatedtask_time_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedtask',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='generatedtask',
            name='time_update',
        ),
    ]
