# Generated by Django 4.2 on 2023-06-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0010_remove_generatedtask_time_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedtask',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата составления'),
        ),
        migrations.AddField(
            model_name='generatedtask',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
