# Generated by Django 4.2 on 2023-06-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0013_generatedtask_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedtask',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
