# Generated by Django 4.2 on 2023-06-03 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0022_alter_task_task_type_alter_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='level',
            field=models.CharField(choices=[('H', 'Сложный'), ('M', 'Средний'), ('L', 'Базовый')], max_length=50, null=True, verbose_name='Уровень сложности'),
        ),
        migrations.AlterField(
            model_name='task',
            name='linked_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='informatica.task', verbose_name='К заданию (прикрепить)'),
        ),
    ]
